hm:
  db:
    host: 127.0.0.1
    un: root
    pw: 123456
    port: 3306
    database: hm-trade
  swagger:
    title: 黑马商城交易接口文档
    description: 黑马商城交易接口文档
    email: e69d8e1026@gmail.com
    concat: li
    package: com.hmall.trade.controller