hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
  db:
    host: 127.0.0.1
    un: root
    pw: 123456
    port: 3306
    database: hm-user
  swagger:
    title: 黑马商城用户接口文档
    description: 黑马商城用户接口文档
    email: e69d8e1026@gmail.com
    concat: li
    package: com.hmall.user.controller