#hm:
#  db:
#    host: 192.168.6.100 # 修改为你自己的虚拟机IP地址
#    pw: 123 # 修改为docker中的MySQL密码

hm:
  db:
    host: 127.0.0.1
    un: root
    pw: 123456
    port: 3306
    database: hm-cart
  swagger:
    title: 黑马商城购物车接口文档
    description: 黑马商城个购物车接口文档
    email: e69d8e1026@gmail.com
    concat: li
    package: com.hmall.cart.controller