server:
  port: 8000
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: 127.0.0.1
    gateway:
      routes:
        - id: item # 路由规则id，自定义，唯一
          uri: lb://item-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/items/**, /search/**
        - id: trade
          uri: lb://trade-service
          predicates:
            - Path=/orders/**
        - id: cart
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
        - id: pay
          uri: lb://pay-service
          predicates:
            - Path=/pay-orders/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/users/**, /addresses/**
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123
