server:
  port: 8081
feign:
  sentinel:
    enabled: true
hm:
  db:
    host: 127.0.0.1
    un: root
    pw: 123456
    port: 3306
    database: hm-item
  swagger:
    title: 黑马商城商品接口文档
    description: 黑马商城商品接口文档
    email: e69d8e1026@gmail.com
    concat: li
    package: com.hmall.item.controller

##   配置服务注册中心地址
#  cloud:
#    nacos:
#      server-addr: 192.168.6.100:8848
#  profiles:
#    active: dev
#  datasource:
#    url: jdbc:mysql://${hm.db.host}:3306/hm-item?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: ${hm.db.pw}
#mybatis-plus:
#  configuration:
#    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
#  global-config:
#    db-config:
#      update-strategy: not_null
#      id-type: auto
#logging:
#  # 日志级别
#  level:
#    com.hmall: debug
#  pattern:
#    dateformat: HH:mm:ss:SSS
#  file:
#    path: "logs/${spring.application.name}"
#knife4j:
#  enable: true
#  openapi:
#    title: 黑马商城接口文档
#    description: "黑马商城商品管理接口文档"
#    email: zhanghuyi@itcast.cn
#    concat: 虎哥
#    url: https://www.itcast.cn
#    # /doc.html
#    version: v1.0.0
#    group:
#      default:
#        group-name: default
#        api-rule: package
#        api-rule-resources:
#          - com.hmall.item.controller

